### ISSUE TITLE
LSM9DS0 : gyro and magnetometer sensors use the wrong units

### ISSUE THREAD

**Issue by baudhuina** [adafruit/Adafruit_LSM9DS0_Library#10]
- gyro values are reported by the sensor in degree per second instead of radian per second, as specified at [https://learn.adafruit.com/using-the-adafruit-unified-sensor-driver/how-does-it-work](url)
- magnetometer values are reported by the sensor in gauss and not in µTesla (cf. [https://forums.adafruit.com/viewtopic.php?f=25&t=137966&p=683683#p683683](url)

**Comment by ladyada** [comment]
pardon the delay - this sensor is no longer made. fixed now.
