### ISSUE TITLE
Wrong temperature output

### ISSUE THREAD

**Issue by Tellicious** [adafruit/Adafruit_LSM9DS0_Library#3]
the temperature given by readTemp() is not correct: the datasheet reports that the temperature sensor sensitivity is 8 LSB/°C (page 15) but they forgot to mention what the intercept is. It seems to lie between 20°C and 22°C.
The correct output should be: temperature = xhi*0.125 + intercept; and temperature has to be declared as float. I didn't open a pull request since I'm not sure about what the intercept is.

**Comment by kevnd** [comment]
This is addressed in the FAQ on the Adafruit website:
https://learn.adafruit.com/adafruit-lsm9ds0-accelerometer-gyro-magnetometer-9-dof-breakouts/faqs

**Comment by ladyada** [comment]
cleaning up old issues
