### ISSUE TITLE
Adafruit LSM9DS0 Library error for Adafruit Flora board

### ISSUE THREAD

**Issue by olyarybalko** [adafruit/Adafruit_LSM9DS0_Library#7]
Hello, for this setup  Adafruit Flora + FLORA 9-DOF Accelerometer/Gyroscope/Magnetometer.
I have the Library error:
Adafruit LSM9DS0 Library/Adafruit_LSM9DS0.cpp.o: In function `Adafruit_LSM9DS0::begin()':
/root/Arduino/libraries/Adafruit_LSM9DS0_Library-master/Adafruit_LSM9DS0.cpp:79: undefined reference to `operator delete(void*, unsigned int)'
collect2: error: ld returned 1 exit status
Error compiling.

Thank you

**Comment by ladyada** [comment]
could not reproduce if you have latest IDE 1.82, latest Adafruit Boards 1.4.9, and latest library!
